name: 'project_dbtcore'
version: '1.0.0'
config-version: 2

profile: 'dbtcore_pg'

model-paths: ["models"]

models:
  project_dbtcore:
    raw:
      +materialized: view
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +schema: 'gold'
      +materialized: table